admin_login:
    path: /admin/login
    controller: App\AdminPanel\Controller\AdminLoginController::login

admin_login_check:
    path: /admin/login_check
    # Handled by Symfony security component

admin_logout:
    path: /admin/logout
    # Handled by Symfony security component

admin_dashboard:
    path: /admin
    controller: App\AdminPanel\Controller\AdminDashboardController::index

admin_process_lead:
    path: /admin/process-lead/{id}
    controller: App\AdminPanel\Controller\ProcessLeadController::process
    requirements:
        id: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' # UUID format 