admin_login:
    path: /admin/login
    controller: App\AdminPanel\Controller\AdminLoginController::login

admin_login_check:
    path: /admin/login_check
    # Handled by Symfony security component

admin_logout:
    path: /admin/logout
    # Handled by Symfony security component
