controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_panel:
    resource:
        path: ../src/AdminPanel/Controller/
        namespace: App\AdminPanel\Controller
    type: attribute
